### ISSUE TITLE
bug: Descrição e Corpo de um artigo está quebrando a página horizontalmente

### ISSUE THREAD

**Issue by irmaosdev1** [irmaos-dev/mural#16]
## Descreva o bug

Uma descrição precisa e concisa do problema

## Como reproduzir

Descreva os passos necessários para reproduzir o problema

1. Crie um com um texto ou descrição muito grande e sem espaços.
2. Abra o artigo

## Comportamento esperado
Quebrar o texto horizontalmente no limite do container ou div

## Screenshots (optional)

![image](https://github.com/user-attachments/assets/e50cb580-ecd0-4501-b3cc-c3cdfb31cb7c)

**Comment by JD-Rodrigues** [comment]
Posso fazer esta?

**Comment by marcelaodev** [comment]
@JD-Rodrigues 

devido ao seu perfil, seria mais interessante fazer uma task de Senior
mas se quiser pode ^^

**Comment by JD-Rodrigues** [comment]
@marcelaodev Certo. Vou buscar uma de senior que eu consiga dar conta.
