### ISSUE TITLE
chore: Atualizar o projeto base do Back-End para permitir o uso do Laravel 11

### ISSUE THREAD

**Issue by irmaosdev1** [irmaos-dev/mural#20]
## Descreva o problema que você quer resolver com essa feature

No momento, nosso projeto está usando o Laravel 9 e algumas funcionalidades importantes do framework podem estar indisponíveis para nós.

## Descreva como você vê uma solução

Atualizar o projeto para permitir o uso do Laravel 11

**Comment by Elivandro** [comment]
tô fazendo esse...
