### ISSUE TITLE
feat: Atualização em tempo real

### ISSUE THREAD

**Issue by irmaosdev1** [irmaos-dev/mural#24]
## Descreva o problema que você quer resolver com essa feature

Para ver um novo artigo que foi postado, é necessário mudar ou atualizar a página.

## Descreva como você vê uma solução

Utilize websockets para notificar o front-end que é necessário fazer um novo fetch.
Contudo, o backend deve enviar essa notificação em intervalos mínimos para evitar a realização de requisições muito frequentes.

## Critério de aceite

- Abra uma aba no feed global
- Abra uma nova aba na criação de artigos
- Crie um artigo
- Verifique na primeira aba que o artigo criado foi exibido sem atualizar a página

**Comment by irmaosdev1** [comment]
@igormarinho98

**Comment by irmaosdev1** [comment]
https://laravel.com/docs/11.x/broadcasting

**Comment by irmaosdev1** [comment]
esboço do fluxo

![image](https://github.com/user-attachments/assets/ff09f2e3-da32-434d-af32-eb6324dc5abd)

**Comment by igormarinho98** [comment]
Fiz a primeira

**Comment by igormarinho98** [comment]
estou analisando como sera feita a implementacao

**Comment by igormarinho98** [comment]
.

**Comment by igormarinho98** [comment]
fechei sem querer

**Comment by igormarinho98** [comment]
estudando implementação usando o exemplo da doc https://laravel.com/docs/9.x/broadcasting

**Comment by igormarinho98** [comment]
Instalando dependencias do front e no back end para utilizar websockets

**Comment by igormarinho98** [comment]
![image](https://github.com/user-attachments/assets/e91553ce-6b69-45fe-ad8d-49e2a246c99d)

Ao instalar dependencia pusher-js me retorna o erro que a versão do node requerida é 18, 

Enquanto nosso projeto roda no 16
