### ISSUE TITLE
chore: configurar OpenTelemetry no projeto

### ISSUE THREAD

**Issue by irmaosdev1** [irmaos-dev/mural#29]
## Descreva o problema que você quer resolver com essa feature

Descreva de forma concisa do porquê essa funcionalidade é importante. Ex: "Eu sempre me frustro quando vou fazer 'X', poder fazer 'Y' deixaria a experiência muito melhor."

## Descreva como você vê uma solução

Descreva de forma conscisa como solucionar seu problema. Ex: seria bom se quando estiver na tela 'X', eu pudesse clicar em um botão 'P' que faz 'Y'.

**Comment by irmaosdev1** [comment]
Você pode dividir essa tarefa em dois e implementar apenas a parte que lhe convém: backend ou frontend.

**Comment by JD-Rodrigues** [comment]
Olá, Marcelo! Vou tentar implentar isso no Laravel. Se der certo, farei no front.

**Comment by irmaosdev1** [comment]
@JD-Rodrigues 
infelizmente ainda não consegui fazer funcionar propriamente.
Tem o Laravel Telescope pra dar esse tipo de informação que nós temos interesse em ver.
Estou pensando em deixar o Open Telemetry de lado e focar no Telescope.
Lamento pelo tempo desperdiçado nessa issue.

**Comment by JD-Rodrigues** [comment]
Tranquilo. Para mim não foi desperdiço, pois eu nunca tinha mexido com isso. Pude ter uma ideia. Em uma necessidade futura já terei uma noção.
