### ISSUE TITLE
bug: Foto de perfil padrão

### ISSUE THREAD

**Issue by irmaosdev1** [irmaos-dev/mural#42]
## Descreva o bug

Quando criamos um novo usuário, ele vem com uma foto de perfil "quebrada".

## Como reproduzir

Crie um novo usuário e verifique no canto superior direito que não é exibido uma foto de perfil.

## Comportamento esperado

Quando um usuário não possui uma foto de perfil, deveria ser exibido uma imagem padrão no lugar.

## Screenshots (optional)

![image](https://github.com/user-attachments/assets/e397a0f1-3f5e-4c41-9a79-229723ed59bb)

**Comment by irmaosdev1** [comment]
@Edsonromeumaier

**Comment by Edsonromeumaier** [comment]
## Estou

**Comment by irmaosdev1** [comment]
Essa tarefa foi cancelada porque decidimos usar sempre a foto de perfil vinda do Google.
