### ISSUE TITLE
feat: Colocar foto para o artigo

### ISSUE THREAD

**Issue by irmaosdev1** [irmaos-dev/mural#43]
## Descreva o problema que você quer resolver com essa feature

Não é possível colocar uma foto para representar o conteúdo do artigo. A parte visual é importante.

## Descreva como você vê uma solução

Possibilitar o upload de um imagem e exibí-la no feed conforme a screenshot abaixo.
A imagem deve ser clicável e redirecionar o usuário para a página do artigo.
A imagem também deverá ser exibida na página do artigo.
Definir o posicionamento final da imagem tanto no feed quanto na página do artigo.

![image](https://github.com/user-attachments/assets/768d8326-f2fd-4f2a-8fe8-b81c4d28113f)

**Comment by daniellacortes** [comment]
Essa é minha! Por favor, Marcelo, atribua para mim!

**Comment by daniellacortes** [comment]
Essa task é mim! Por favor, Marcelo, atribua para mim!
