### ISSUE TITLE
[Dívida Técnica] Campos nulos do User estão sendo forçados a usarem uma string vazia na serialização

### ISSUE THREAD

**Issue by moreirayokoyama** [irmaos-dev/mural#45]
O model `User` possui os campos `bio` e `image` que são modelados como _nullable_. Apesar disto, no momento da serialização, o resource está forçando uma string vazia. Isto se deve ao commit 664010c, que fez esta alteração.

## Descrição da dívida técnica
Qualquer efeito colateral que a aplicação possa ter na serialização do model deveria estar explícita no próprio Model. Se o Model declara o campo como _nullable_, a serialização deveria suportar valores nulos. Se a serialização não pode suportar valores nulos, então é um sinal de que a boa prática levar esta constraint para o Model e tratá-la.

## Sugestões de como pagar a dívida
- Remover o suporte a valores nulos nos campos `bio` e `image`
    - Tornar os campos não _nullable_ e usar valores padrão para serem atribuídos ao model
    - Desfazer a alteração do commit 664010c, que força uma string vazia na serialização
- Permitir a serialização dos valores nulos
    - remover o tratamento que força uma string vazia nos campos `bio` e `image`
    - criar testes específicos para cenários com valores nulos, fazendo um _assert_ garantindo a ausência dos campos.

**Comment by irmaosdev1** [comment]
corrigido no commit 38b99cbab2413d3e60add149d5af6a92e7a3e905
