### ISSUE TITLE
chore: Adicionar .env no frontend e substituir os endereços da API por variáveis de ambiente

### ISSUE THREAD

**Issue by marcelaodev** [irmaos-dev/mural#51]
## Descreva o problema que você quer resolver com essa feature

Descreva de forma concisa do porquê essa funcionalidade é importante. Ex: "Eu sempre me frustro quando vou fazer 'X', poder fazer 'Y' deixaria a experiência muito melhor."

## Descreva como você vê uma solução

Descreva de forma conscisa como solucionar seu problema. Ex: seria bom se quando estiver na tela 'X', eu pudesse clicar em um botão 'P' que faz 'Y'.

**Comment by JD-Rodrigues** [comment]
Deixa essa comigo ;)

**Comment by irmaosdev1** [comment]
https://github.com/irmaos-dev/mural/pull/55
