### ISSUE TITLE
Enviar comentário ao apertar Ctrl + Enter

### ISSUE THREAD

**Issue by irmaosdev1** [irmaos-dev/mural#59]
## Descreva o problema que você quer resolver com essa feature

Gostaria de ter mais agilidade no momento de fazer um comentário.

## Descreva como você vê uma solução

Enviar o comentário ao apertar Ctrl + Enter

**Comment by irmaosdev1** [comment]
dojasoijasdjoi

**Comment by luizaugusto527** [comment]
ddd

**Comment by angelorubin** [comment]
Olá, vou implementar essa funcionalidade.
