### ISSUE TITLE
Artigos não aceitam "unfavorite"

### ISSUE THREAD

**Issue by daniellacortes** [irmaos-dev/mural#64]
## Descreva o bug

Quando se tenta desfavoritar um artigo, ele não aceita o comando. Ademais, não aparece o botão favoritar para o usuário admin.

## Como reproduzir

Abrir um artigo, favoritar o artigo e desfavoritar. Observe que o artigo continuará como favorito. O erro também pode ser reproduzido no feed de artigos favoritos repetindo o mesmo procedimento.

## Comportamento esperado
Espera-se que ao clicar em "unfavorite" o artigo seja removido dos favoritos e o botão que está com fundo verde e escrito "Unfavorite article" alterne para fundo transparente e dizeres "Favorite article", conforme ordem inicial.

**Comment by luizaugusto527** [comment]
posso pegar essa task?

**Comment by luizaugusto527** [comment]
posso pegar essa task?

**Comment by irmaosdev1** [comment]
@luizaugusto527 que tal alguma dessas outras tasks?

https://github.com/irmaos-dev/mural/issues?q=is%3Aopen+is%3Aissue+label%3ASenior

vi que você já trabalha na área então seria interessante uma task nível senior
outra ideia é fazer um code review nessa aqui https://github.com/irmaos-dev/mural/pull/67

**Comment by luizaugusto527** [comment]
Foi mal, não vi que era pra júnior. Comentei nessa aqui [#61](https://github.com/irmaos-dev/mural/issues/61)

**Comment by daniellacortes** [comment]
Adicionado na descrição: Ademais, não aparece o botão favoritar para o usuário admin.

**Comment by daniellacortes** [comment]
Vou ficar com essa tarefa.
