### ISSUE TITLE
Componente de erro do client não exibe a mensagem do server

### ISSUE THREAD

**Issue by irmaosdev1** [irmaos-dev/mural#69]
## Descreva o bug

Ao informar um erro do sistema no client, ele exibe apenas uma mensagem genérica, em vez de transmitir a mensagem do server.

## Como reproduzir

Existem várias formas, mas uma é:

1. Altere a senha do banco de dados no .env do server
2. Rode o client e a mensagem genérica deve aparecer.

## Comportamento esperado

Gostaria que o "message" recebido do server fosse exibido **caso a aplicação esteja em ambiente de desenvolvimento**.

## Screenshots (optional)

Componente de erro genérico:
![image](https://github.com/user-attachments/assets/0334a825-73f9-4df6-baec-1f40232bd3e8)

Mensagem vinda do server:
![image](https://github.com/user-attachments/assets/a9ca9f24-658f-4b0d-8128-f930dd531dbf)

**Comment by RuanSalles** [comment]
Eu aconselharia, dentro do controller que está sendo chamado pelo método encapsular o método com um try catch, da seguinte maneira:

Try {
joga a implementação aqui dentro
} catch (Exception $e) {
return response()->json($e->getMessage)
}

Assim você fará com que o erro seja tratado e jogado como resposta para o Front-End

**Comment by cristianoapps** [comment]
Minha sugestão é parecida com a do amigo @RuanSalles. Minha sugestão é, criar uma variavel de estado no topo do componente que chama a api , essa variável pode se chamar error, conforme exemplo abaixo

const [error, setError] = useState(null);

logo após, na implementação da chamada da api, envolver o método com um try catch para capturarmos a exceção que vem do backend, por exemplo :

 const pegarDadosBack= async () => {
    try {
      setError(null); 
     await fetchDataFromApi();
    } catch (err) {
      setError(err.message); // Nessa linha você seta o erro obtido na chamada da api, caso realmente exista erro
    }
  };

Logo após, basta mostrar na div o valor que está no estado error

error && <div>Erro que apareceu ${error}</div>
