### ISSUE TITLE
feat: Login Social

### ISSUE THREAD

**Issue by irmaosdev1** [irmaos-dev/mural#7]
## Descreva o problema que você quer resolver com essa feature

No momento, nossa aplicação base aceita o cadastro de usuários apenas pelo email/senha.

## Descreva como você vê uma solução

- Remover a possibilidade de cadastro/login utilizando email/senha.
- Utilizar o Single Sign-On do Google para o cadastro/login do usuário.
- Utilizar o nome no Google como o nome de usuário no app.
- Utilizar a foto de perfil do Google como a foto de perfil no app.

**Comment by marcelaodev** [comment]
@daniellacortes
