### ISSUE TITLE
Permitir títulos iguais

### ISSUE THREAD

**Issue by daniellacortes** [irmaos-dev/mural#77]
## Descreva o problema que você quer resolver com essa feature

O sistema somente aceita títulos diferentes. Seria interessante autorizar que artigos pudessem ter o mesmo título.

## Descreva como você vê uma solução

Retirar a restrição no banco de dados backend.
Porém, nós trabalhamos com o conceito de "slug" para acessar um artigo específico. O slug coincide com o título do artigo. Portanto, precisaremos modificar a atribuição do slug para um artigo. Fazer similar ao nome de usuário: adicionar um pequeno ID na frente do slug.
Exemplo:
Dois artigos com título "Teste". O primeiro a ser criado, o slug pode ser simplesmente "teste". O segundo deve ser algo do tipo: "teste-d3e".

**Comment by irmaosdev1** [comment]
Esse pacote aqui gera o slug, garantindo que o titulo possa ser igual e ainda assim o slug seja diferente.

https://github.com/cviebrock/eloquent-sluggable

Seria interessante também substituir a geração de slug que usamos no momento para criar o usuário (a Dani criou isso na mão no GoogleLogin).
