### ISSUE TITLE
Adicionar modal de Confirmar Deletar

### ISSUE THREAD

**Issue by irmaosdev1** [irmaos-dev/mural#89]
## Descreva o problema que você quer resolver com essa feature

Um clique não-intencional no botão de deletar faz com que o artigo ou comentário sejam deletados para sempre.
É um padrão nas aplicações web ter um pedido de confirmação para deletar alguma entidade.

## Descreva como você vê uma solução

Colocar uma modal de confirmação ao clicar em um botão de deletar artigo ou comentário.

**Comment by devguilara** [comment]
Boa tarde @irmaosdev1  gostaria de atuar nessa issue.

**Comment by irmaosdev1** [comment]
@devguilara é isso mesmo.
vc pode ver que o dropdown foi criado pelo @moises-elias nessa mesma estrutura de pastas
